### ISSUE TITLE
[Suggestion] Tooglable mass farming.

### ISSUE THREAD

**Issue by BentoGambin** [blaxxun-boop/Farming#4]
Hey, the new multiple-planting feature is very nice, but it causes errors with farm grid. Also, is it possible to make it so that instead of having to hold the shift key to be able to plant a single crop, you could press a button and it would toggle between 'single' and 'multi' mode.
Thanks in advance.

**Comment by virtualbjorn** [comment]
Would love to see this added! Would be great if its compatible with Mass Farming / Farm Grid too.

**Comment by blaxxun-boop** [comment]
I made the mass plant mode a toggle, rather than having to hold down the key for single plant in v1.2.2.

However, I cannot make the mod compatible with mass farming, because it's exactly the same code. I copied the mass farming code into Farming, because the author gave permission to do so.

**Comment by virtualbjorn** [comment]
That's understandable, is it possible to have it snap to an existing grid? Even without FarmGrid mod. Currently FarmGrid works but it makes a weird snapping point because of how the center is adjusted for mass planting. i.e mass planting a 2*2 snaps to an existing grid but skewed a little bit to half of the currently planted grid.
